[build]
  command = "npm run build:secure"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[dev]
  framework = "vite"


